### ISSUE TITLE
Adding additional configuration possibilities for parameters 

### ISSUE THREAD

**Issue by destogl** [pac48/gen_param_struct#1]
Thanks for very interesting package. It would be very cool to have a possibility to define more of parameters, e.g., type, min, max, description etc. Would it be possible to extend the YAML file for generating the structure in something like [config files from rosparam_handler](https://github.com/cbandera/rosparam_handler/blob/develop/test/cfg/Defaults.params) or [this one here](https://github.com/cbandera/rosparam_handler/blob/develop/test/cfg/MinMax.params)?

**Comment by pac48** [comment]
I do think it will be possible. My current plan is to use the yaml dictionary type to define these extra attributes. For example: 
```
stiffness: {
      default_values: [.NAN, .NAN, .NAN, .NAN, .NAN, .NAN],
      description: "specifies stiffness values for x, y, z, rx, ry, and rz used in the admittance calculation",
      configurable: true
      optional: false
      bounds: [-.Inf, .Inf]
    }
  ```
The I believe the definition above would allow a struct with the handling you described.

**Comment by pac48** [comment]
I have made the changes needed to define bounds, read only, optional, and a description. You can see a full controller definition [here](https://github.com/pac48/gen_param_struct/blob/main/gen_param_struct_example/include/config/definition.yaml). The user then needs to load [this](https://github.com/pac48/gen_param_struct/blob/main/gen_param_struct_example/include/config/implementation.yaml) parameter file in their node.
