### ISSUE TITLE
Error message for out of bounds should print bounds

### ISSUE THREAD

**Issue by tylerjw** [pac48/gen_param_struct#2]
To help the user know why the out of bounds validation failed, the error string generated should contain the bounds that are valid and the value set.

```Invalid value '{value}' for parameter {name}.  Required bounds: [{lower}/-inf, {upper}/inf]```

**Comment by pac48** [comment]
See https://github.com/pac48/gen_param_struct/commit/64da2751d43225fc7eb178b78465094c15514ca0

**Comment by pac48** [comment]
Once fmt is integrated, it should be used for printing.
